# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

##### RPC and REST configs #####

# RPC endpoint for ethereum chain
eth_rpc_url = "http://localhost:9545"

# RPC endpoint for metis chain
metis_rpc_url = "http://localhost:8545"

# RPC endpoint for tendermint
tendermint_rpc_url = "http://0.0.0.0:26657"

#### Bridge configs ####

# Themis REST server endpoint, which is used by bridge
themis_rest_server = "http://0.0.0.0:1317"

## Poll intervals
root_poll_interval = "15s"
themis_poll_interval = "1s"
metis_poll_interval = "1s"
span_poll_interval = "10s"
respan_poll_interval = "10s"
respan_delay_time = "3m0s"
mpc_poll_interval = "10s"
enable_self_heal = "false"
sh_stake_update_interval = "3h0m0s"
sh_max_depth_duration = "1h0m0s"

#### gas limits ####
main_chain_gas_limit = "30000000"

#### gas price ####
main_chain_max_gas_price = "400000000000"

##### chain  #####
chain = "sepolia"
