apiVersion: v1
kind: Service
metadata:
  name: {{ include "metis-node.fullname" . }}-l1dtl
  labels:
    app: {{ .Release.Name }}-l1dtl-svc
    {{- include "metis-node.labels" . | nindent 4 }}
  {{- with .Values.l1dtl.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.l1dtl.service.type }}
  {{- with .Values.l1dtl.service.ports }}
  ports:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    app: {{ .Release.Name }}-l1dtl
    {{- include "metis-node.selectorLabels" . | nindent 4 }}
