{{- if .Values.l1dtl.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "metis-node.fullname" . }}-l1dtl-env
  labels:
    {{- include "metis-node.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.l1dtl.envFromSecret }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
