apiVersion: v1
kind: Service
metadata:
  name: {{ include "metis-node.fullname" . }}-l2geth
  labels:
    app: {{ .Release.Name }}-l2geth-svc
    {{- include "metis-node.labels" . | nindent 4 }}
  {{- with .Values.l2geth.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.l2geth.service.type }}
  {{- with .Values.l2geth.service.ports }}
  ports:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    app: {{ .Release.Name }}-l2geth
    {{- include "metis-node.selectorLabels" . | nindent 4 }}
