{{- if .Values.l2geth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "metis-node.fullname" . }}-l2geth-env
  labels:
    {{- include "metis-node.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.l2geth.envFromSecret }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
